apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lik5i9vai-dotnet-basic
  janus-idp.io/tekton: lik5i9vai-dotnet-basic
  backstage.io/kubernetes-id: lik5i9vai-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lik5i9vai-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
